### PR TITLE
Infra/unit test

### PR DESCRIPTION
**Pull request by nosmokingsurfer**
Hello Gonzalo,

I think at this moment, there are no things to add to this branch about unit tests for SE3 using catch2. I'd like to merge it into master and have an option to write unit tests for other branches. If you have any requirements on how to integrate catch2 into the repo please share.

### CODE REVIEW

**Comment by anastasiia-kornilova** [comment]
@nosmokingsurfer @g-ferrer-sk 
1. I would add catch2 as submodule and specify path to it in cmake, as was done with pybind and eigen. In that case we could update it with new patches just by updating submodule.
2. Also, maybe it is better to specify building tests with some flag, not to have extra strange executables in final dir (necessary for clean builds of pip-packages and distro-packages).
3. Also, I would propose to add tests execution to CI build to check consistency on every commit for any other contributors.

**Comment by nosmokingsurfer** [comment]
@anastasiia-kornilova Thanks for the feedback, Anastasia. I agree with you, all the points are reasonable. I think I can handle the first two but will need help with CI. By CI you mean the checks that are done on the github side?

**Comment by anastasiia-kornilova** [comment]
@nosmokingsurfer 

Yes, by CI I mean Continuous Integration that currently is performed using services Circle CI (https://circleci.com/) and Github Actions (https://github.com/features/actions). At some moment, I hope, we will choose and migrate to only one. The main thing, that they provide, is a library build on clean machines with a wide variety of OS and distributives. Also, using this service mrob now has an option to build pip-packages and automatically deploy them to the PyPI repository without any manual work.

I would propose to start with Circle CI. Its config is there -- https://github.com/MobileRoboticsSkoltech/mrob/blob/master/.circleci/config.yml, you could look through it -- it actually just specifies machine, install packages, build the library and run python examples, and finally creates pip-package and tests it. The current run of python examples as tests is quite dirty, but they allow to check that at least syntactically nothing was ruined. Of course, the tests you are doing are more suitable there.

The job you need to modify is "build" -- https://github.com/MobileRoboticsSkoltech/mrob/blob/f08e88c98bb7703f34504616fabf7fdb1755238a/.circleci/config.yml#L4 , I suppose just to add step "run" in the end with running your compiled test executables. You could go to the "Details" (I attached a screenshot with this panel) of "build" job on Circle CI and take a look at how it is performed.

Any questions are welcome, proper testing is what mrob is missing a lot :) 

Selection_999(772)

**Comment by g-ferrer-sk** [comment]
ok, I'm checking things. Should you change directly git .submodule?? it seems odd since you are adding it later.

**Comment by nosmokingsurfer** [comment]
@g-ferrer-sk 

> ok, I'm checking things. Should you change directly git .submodule?? it seems odd since you are adding it later.

I first tried to add Catch2 manually into ```.gitmodules``` but it didn't work for the test machine - it didn't check out Catch2. It looks like the right way is to do the ```git submodule add ... ``` command and something happens in the git index then and all the records added into the ```.gitmoduls```. Besides that, I've experimented with this ```submodule add ... ``` in separate checkout and accidentally pushed from there and then returned to the original one and it was already outdated. There was some merging errors. I'm not experienced with git branching and managing yet. Anyway, I guess after squishing all these small ugly commit history should go away.

**Comment by nosmokingsurfer** [comment]
@g-ferrer-sk @anastasiia-kornilova 

Hello, this PR is finalized and ready to be merged.

**Comment by nosmokingsurfer** [comment]
@g-ferrer-sk 
oh, I should change the README.md now to point out that there is additional dependency on Catch2 now

**Pull request merged**
